name: Revalidating

on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Revalidating"
        run: curl https://ush.vercel.app/api/revalidate
